### ISSUE TITLE
Unable to load Annotations on my own data

### ISSUE THREAD

**Issue by madeluis** [MoMI-G/MoMI-G#58]
Hello,

I have been trying to visualize some tomato data using MoMI-G. I have been successful loading and visualizing all my files (xg and pcf) except for the annotation file. So basically, the circos plot, the feature table, and the SequenceTubeMap are working properly, but the "LinearView:Annotations" sections simply shows "No Data".  

I have tried loading the annotation as a gff file, as a bed file, and as a bigbed file, and none of those seem to work. I have also tried to include the annotation file under the "reference" section in the config.yaml file, and I later tried moving it under the static_files section, but again, none of those are working. Here is my current config.yaml file (here I have the annotation in two spots to show the two spots where I've tried including it):

`bin:
  vg: "vg"
  vg_tmp: "vg"
  graphviz: "dot"
  fa22bit: "faToTwobit"
  bigbed: "bedToBigBed"
reference:
  chroms: "static/tomatoCHR.json"
  data:
    - name: "SL4"
      features:
        - name: "gene_annotation"
          url: "static/ITAG4.0_gene_models.bb"
          chr_prefix: "SL4.0ch"
data:
  - name: "tomato_BGV006336"
    desc: "2021-01-25"
    chr_prefix: ""
    ref_id: "SL4"
    source:
      xg: "static/data.xg"
      csv: "static/clean_BGV006336.tomato_graphFile.pcf"
    features: []
    static_files:
      - name: 'Genes'
        url: 'static/ITAG4.0_gene_models.bb'
        viz: 'bigbed'`

Also, the annotations in your current demo page are not working on my end either --any chance that these two issues are related?

I would really appreciate any input on this issue. Thanks in advance!!

**Comment by 6br** [comment]
Thank you for using MoMI-G.

Currently, `Linear View: Annotation` displays genomic features on `reference.data.features` on `config.yaml` and it works only if the input is gff3 or bed format. And bigbed is not supported for `reference.data.features` section.

https://momi-g.readthedocs.io/en/latest/configure_file.html#example

```
reference:
  chroms: "static/GRCh.json"
  data:
    - name: "hg19"
      features:
        - name: 'gene_annotation'
          url: "test/gencode.v25.basic.annotation.Y.bed"
          chr_prefix: "chr"
    - name: "hg38"
      features:
        - name: 'gene_annotation'
          url: "test/gencode.v25.basic.annotation.Y.bed"
          chr_prefix: "chr"
```

If you wish to use GFF format, all header lines need to be removed by `grep -v "#"` in advance. 

```
reference:
  chroms: "static/GRCh.json"
  data:
    - name: "hg19"
      features:
        - name: 'gene_annotation'
          url: 'test/gencode.v26.chr_patch_hapl_scaff.basic.annotation.wo.header.head.gff3'
          chr_prefix: "chr"
    - name: "hg38"
      features:
        - name: 'gene_annotation'
          url: 'test/gencode.v26.chr_patch_hapl_scaff.basic.annotation.wo.header.head.gff3'
          chr_prefix: "chr"
```

Also, the demo page is now running without annotations due to some technical reason. 
Sorry for not documented this.

**Comment by 6br** [comment]
Now the No data on demo page is fixed. Thank you for reporting us.

**Comment by madeluis** [comment]
Hello,

Thanks so much for your reply.
I pulled the newest commit of the repository (in case your fix to the demo page was made from the source code and it was affecting me as well), and I changed  the file that I am using for the annotations. I tried using a bed file and later I tried using a gff file without headers, as you indicated.

Here is my config.yaml file:

`bin:
  vg: "vg"
  vg_tmp: "vg"
  graphviz: "dot"
  fa22bit: "faToTwobit"
  bigbed: "bedToBigBed"
reference:
  chroms: "static/tomatoCHR.json"
  data:
    - name: "SL4"
      features:
        - name: "gene_annotation"
          url: "static/ITAG4.0_gene_models_noHeader.gff"
          chr_prefix: "SL4.0ch"
data:
  - name: "tomato_BGV006336"
    desc: "2021-01-25"
    chr_prefix: ""
    ref_id: "SL4"
    source:
      xg: "static/data.xg"
      csv: "static/merged.tomato_graphFile.pcf"
    features: []
    static_files: []
`

Unfortunately, this hasn't resolved the issue. 

In addition, I continue to have a problem with the "Linear View: Annotation" in the demo page: when I first load the page, the annotations appear correctly for the loci that is being displayed by default. However, if I select any other loci, it continues to show "No Data".

Please, let me know if you have any further insights into this issue. 

Thanks again!

**Comment by 6br** [comment]
For config.yaml:

Is it possible to add `.bb` file on `data.features` section?

```
bin:
  vg: "vg"
  vg_tmp: "vg"
  graphviz: "dot"
  fa22bit: "faToTwobit"
  bigbed: "bedToBigBed"
reference:
  chroms: "static/tomatoCHR.json"
  data:
    - name: "SL4"
      features:
        - name: "gene_annotation"
          url: "static/ITAG4.0_gene_models.gff3"
          chr_prefix: "SL4.0ch"
data:
  - name: "tomato_BGV006336"
    desc: "2021-01-25"
    chr_prefix: ""
    ref_id: "SL4"
    source:
      xg: "static/data.xg"
      csv: "static/clean_BGV006336.tomato_graphFile.pcf"
    features: 
      - name: "gene_annotation"
        url: "static/ITAG4.0_gene_models.bb"
        chr_prefix: "SL4.0ch"
    static_files:
      - name: 'Genes'
        url: 'static/ITAG4.0_gene_models.bb'
        viz: 'bigbed'`

```

There is a way to check if the backend works well or not. For example, in our demo backend, the annotation against `chr20:312898-32302312` can be retrieved from demo backend in the following commands:

```bash
$ docker run --rm --init -p 8081:8081 momigteam/momig-backend   #wait until `Start server on 0.0.0.0:8081` is displayed.
$ curl "localhost:8081/api/v2/region?format=bed&path=chr1:0-200003"
{"static/ensGene.bb":[{"start_offset":4273,"stop_offset":19669,"id":0,"name":"gene_annotation","is_reverse":null,"attributes":["ENST00000326632","0","-","19669","19669","0","13","92,39,106,44,139,18,198,132,141,147,99,155,273,","0,589,1385,1493,2196,2337,2447,2822,3191,3504,3857,10326,15123,","ENSG00000146556","Q9H7N0_HUMAN"],"value":null},{"start_offset":42911,"stop_offset":44799,"id":1,"name":"gene_annotation","is_reverse":null,"attributes":["ENST00000359752","0","+","44799","44799","0","2","19,107,","0,1781,","ENSG00000197490","null"],"value":null},{"start_offset":52877,"stop_offset":53750,"id":2,"name":"gene_annotation","is_reverse":null,"attributes":["ENST00000379479","0","+","53750","53750","0","1","873,","0,","ENSG00000205292","OR4G11P"],"value":null},{"start_offset":58953,"stop_offset":59871,"id":3,"name":"gene_annotation","is_reverse":null,"attributes":["ENST00000326183","0","+","58953","59871","0","1","918,","0,","ENSG00000177693","OR4F5"],"value":null},{"start_offset":147646,"stop_offset":147749,"id":4,"name":"gene_annotation","is_reverse":null,"attributes":["ENST00000386603","0","-","147749","147749","0","1","103,","0,","ENSG00000209338","null"],"value":null}]}
```


For demo page:
"No data" is shown if there is no annotation on the selected loci.
For example, when I select a known gene position as loci, annotation will be shown.
<img width="1424" alt="screenshot" src="https://user-images.githubusercontent.com/12047794/108447787-d8f36e80-72a3-11eb-9b06-a019e28be4ad.png">
